<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="5" hostname="NOTE-FBJF011" id="0" name="DeveloperControllerTests" package="br.cesjf.dps" tests="8" time="4.599" timestamp="2013-05-03T16:29:48">
      <properties />

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testSave" time="2.598">
          <failure message="Assertion failed: &#xa;&#xa;assert response.redirectedUrl == &apos;/developer/show/1&apos;&#xa;       |        |             |&#xa;       |        null          false&#xa;       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@585b045d&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert response.redirectedUrl == &apos;/developer/show/1&apos;
       |        |             |
       |        null          false
       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@585b045d

	at br.cesjf.dps.DeveloperControllerTests.testSave(DeveloperControllerTests.groovy:48)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testUpdate" time="0.622">
          <failure message="Assertion failed: &#xa;&#xa;assert developer.save() != null&#xa;       |         |      |&#xa;       |         null   false&#xa;       br.cesjf.dps.Developer : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert developer.save() != null
       |         |      |
       |         null   false
       br.cesjf.dps.Developer : (unsaved)

	at br.cesjf.dps.DeveloperControllerTests.testUpdate(DeveloperControllerTests.groovy:100)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testDelete" time="0.111">
          <failure message="Assertion failed: &#xa;&#xa;assert developer.save() != null&#xa;       |         |      |&#xa;       |         null   false&#xa;       br.cesjf.dps.Developer : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert developer.save() != null
       |         |      |
       |         null   false
       br.cesjf.dps.Developer : (unsaved)

	at br.cesjf.dps.DeveloperControllerTests.testDelete(DeveloperControllerTests.groovy:144)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testCreate" time="0.098" />

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testEdit" time="0.095">
          <failure message="Assertion failed: &#xa;&#xa;assert developer.save() != null&#xa;       |         |      |&#xa;       |         null   false&#xa;       br.cesjf.dps.Developer : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert developer.save() != null
       |         |      |
       |         null   false
       br.cesjf.dps.Developer : (unsaved)

	at br.cesjf.dps.DeveloperControllerTests.testEdit(DeveloperControllerTests.groovy:80)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testShow" time="0.094">
          <failure message="Assertion failed: &#xa;&#xa;assert developer.save() != null&#xa;       |         |      |&#xa;       |         null   false&#xa;       br.cesjf.dps.Developer : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert developer.save() != null
       |         |      |
       |         null   false
       br.cesjf.dps.Developer : (unsaved)

	at br.cesjf.dps.DeveloperControllerTests.testShow(DeveloperControllerTests.groovy:62)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testIndex" time="0.091" />

      <testcase classname="br.cesjf.dps.DeveloperControllerTests" name="testList" time="0.76" />

      <system-out><![CDATA[--Output from testSave--
--Output from testUpdate--
--Output from testDelete--
--Output from testCreate--
--Output from testEdit--
--Output from testShow--
--Output from testIndex--
--Output from testList--
]]></system-out>

      <system-err><![CDATA[--Output from testSave--
--Output from testUpdate--
--Output from testDelete--
--Output from testCreate--
--Output from testEdit--
--Output from testShow--
--Output from testIndex--
--Output from testList--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="NOTE-FBJF011" id="1" name="DeveloperTests" package="br.cesjf.dps" tests="1" time="0.2" timestamp="2013-05-03T16:29:53">
      <properties />

      <testcase classname="br.cesjf.dps.DeveloperTests" name="testSomething" time="0.07">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at br.cesjf.dps.DeveloperTests.testSomething(DeveloperTests.groovy:15)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="5" hostname="NOTE-FBJF011" id="2" name="TaskControllerTests" package="br.cesjf.dps" tests="8" time="1.47" timestamp="2013-05-03T16:29:53">
      <properties />

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testSave" time="0.326">
          <failure message="Assertion failed: &#xa;&#xa;assert response.redirectedUrl == &apos;/task/show/1&apos;&#xa;       |        |             |&#xa;       |        null          false&#xa;       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@766f3ace&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert response.redirectedUrl == &apos;/task/show/1&apos;
       |        |             |
       |        null          false
       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@766f3ace

	at br.cesjf.dps.TaskControllerTests.testSave(TaskControllerTests.groovy:48)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testUpdate" time="0.142">
          <failure message="Assertion failed: &#xa;&#xa;assert task.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       br.cesjf.dps.Task : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert task.save() != null
       |    |      |
       |    null   false
       br.cesjf.dps.Task : (unsaved)

	at br.cesjf.dps.TaskControllerTests.testUpdate(TaskControllerTests.groovy:100)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testDelete" time="0.476">
          <failure message="Assertion failed: &#xa;&#xa;assert task.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       br.cesjf.dps.Task : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert task.save() != null
       |    |      |
       |    null   false
       br.cesjf.dps.Task : (unsaved)

	at br.cesjf.dps.TaskControllerTests.testDelete(TaskControllerTests.groovy:144)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testCreate" time="0.097" />

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testEdit" time="0.083">
          <failure message="Assertion failed: &#xa;&#xa;assert task.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       br.cesjf.dps.Task : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert task.save() != null
       |    |      |
       |    null   false
       br.cesjf.dps.Task : (unsaved)

	at br.cesjf.dps.TaskControllerTests.testEdit(TaskControllerTests.groovy:80)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testShow" time="0.071">
          <failure message="Assertion failed: &#xa;&#xa;assert task.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       br.cesjf.dps.Task : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert task.save() != null
       |    |      |
       |    null   false
       br.cesjf.dps.Task : (unsaved)

	at br.cesjf.dps.TaskControllerTests.testShow(TaskControllerTests.groovy:62)
</failure>

      </testcase>

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testIndex" time="0.08" />

      <testcase classname="br.cesjf.dps.TaskControllerTests" name="testList" time="0.078" />

      <system-out><![CDATA[--Output from testSave--
--Output from testUpdate--
--Output from testDelete--
--Output from testCreate--
--Output from testEdit--
--Output from testShow--
--Output from testIndex--
--Output from testList--
]]></system-out>

      <system-err><![CDATA[--Output from testSave--
--Output from testUpdate--
--Output from testDelete--
--Output from testCreate--
--Output from testEdit--
--Output from testShow--
--Output from testIndex--
--Output from testList--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="NOTE-FBJF011" id="3" name="TaskTests" package="br.cesjf.dps" tests="1" time="0.171" timestamp="2013-05-03T16:29:55">
      <properties />

      <testcase classname="br.cesjf.dps.TaskTests" name="testSomething" time="0.082">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at br.cesjf.dps.TaskTests.testSomething(TaskTests.groovy:15)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="NOTE-FBJF011" id="4" name="TaskTests" package="br.cesjf.tasks" tests="1" time="0.075" timestamp="2013-05-03T16:29:55">
      <properties />

      <testcase classname="br.cesjf.tasks.TaskTests" name="testSomething" time="0.071">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at br.cesjf.tasks.TaskTests.testSomething(TaskTests.groovy:17)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
</testsuites>
